[package]
name = "star-lost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
rand = { version = "0.8.4", features = ["std", "std_rng"] }

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "add1818a05ad4b8d4672197afd477ab29f8446b5"
default-features = false
features = [
    "bevy_gltf", 
    "render", 
    "bevy_winit", 
    "dynamic",
    "x11"
]

[dependencies.bevy_kira_audio]
git = "https://github.com/NiklasEi/bevy_kira_audio"
rev = "9a9a4c87e01ad2fb446852317e63f8fc103406c1"
default-features = false
features = [
  "wav",
  "flac",
  "mp3",
  "ogg",
]